### ISSUE TITLE
The uninstall function doesn't actually uninstall the tools. 

### ISSUE THREAD

**Issue by chris-schmitz** [zce/vue-devtools#2]
Hi, 

I used your package to install the vue-devtools into my electron app. I ran into an error that is coming from vue-devtools and as part of the troubleshooting process I tried to remove vue-devtools from the electron app using your provided uninstall method. 

Regardless of how I attempt the removal it does not actually remove the vue-devtools. Is there a proper way of doing this? Please let me know if there's any other information that I could provide that would be helpful in tracking down this issue. 

The project I'm working on is an opensource app if it helps: https://github.com/chris-schmitz/app-launcher/tree/vue-devtools-issue. I created a new branch and pushed a WIP commit so that you could see the files as they are now. The [electron entry point is here](https://github.com/chris-schmitz/app-launcher/blob/vue-devtools-issue/electronApp/main.js).

![cannotuninstall](https://cloud.githubusercontent.com/assets/2437424/20333233/c2e1bfdc-ab76-11e6-839c-4a96b310e660.gif)

Thanks!

**Comment by zce** [comment]
Already fixed
