### ISSUE TITLE
Keep getting error in electron console.

### ISSUE THREAD

**Issue by EmanueleCoppola** [zce/vue-devtools#21]
I don't know if it's a plugin issue or electron issue.
I'm using electron 6.0.0.

I get this error and the Vue developer tools tab goes full grey.
```
[1] [18987:0806/113757.097861:FATAL:v8_initializer.cc(86)] 
[1] [18992:0806/113834.438401:FATAL:v8_initializer.cc(86)] 
[1] [18996:0806/113922.936504:FATAL:v8_initializer.cc(86)] 
```

**Comment by zce** [comment]
I have already received your question, I will try and give a reply later.

**Comment by zce** [comment]
This does not seem to be a problem with this plugin.

**Comment by zce** [comment]
Please upgrade electron to v6.0.1
