### ISSUE TITLE
version 5.1.1 not loading

### ISSUE THREAD

**Issue by douglassllc** [zce/vue-devtools#25]
I have installed both the npm package and Chrome browser extension for version 5.1.1, but I am still only seeing the older version of vue-devtools load (See image below).  My development environment is Electron v3.1.11.  

<img width="393" alt="vue-devtools-toolbar" src="https://user-images.githubusercontent.com/2228700/63098092-5aad6200-bf72-11e9-8b12-e98435657099.png">

The vue-devtools reads "Ready.  Detected Vue 2.6.10", not sure if this has something todo with why the latest version is not showing.

Here is some additional information that might help.
```
__VUE_DEVTOOLS_INSTANCE_MAP__
size: 71
{"1:4" => Vue, "1:5" => VueComponent, "1:6" => VueComponent, "1:7" => VueComponent, "1:8" => VueComponent, …}
```

Any assistance would be appreciated.

**Comment by zce** [comment]
Due to my negligence, vue-devtools v5.1.1 & v5.1.2 have bugs. Please upgrade to v5.1.3.

**Comment by douglassllc** [comment]
moved this issue to the official repo.  thanks.

**Comment by zce** [comment]
The latest version here uses official 5.1.1.

Whether you can provide a list of all your dependencies, I guess you're probably using different versions at the same time.
