### ISSUE TITLE
vue 脚手架问题

### ISSUE THREAD

**Issue by onlyhappy** [zce/vue-devtools#6]
汪老师，您好，vue脚手架，端口占用，修改端口后，  显示Cannot GET /  不能使用这事怎么回事    有的时候关掉端口，再使用npm run dev之后   有的时候直接报错， 这个问题搞了好几个小时，没有头绪，望老师看到解答下，谢谢

**Comment by zce** [comment]
你好，这里是 vue-devtools 项目提 issue 的地方，请不要把它当成留言板使！！！

**Comment by zce** [comment]
有问题通过其他正常渠道练习我
